texts_choice = {
    
    'Razões para fazer registros': ["""Existem muitas razões pelas quais é importante manter registros regulares e contínuos de sua ansiedade. Em primeiro lugar, ataques de pânico, especialmente aqueles que parecem ocorrer sem motivo aparente, fazem com que as pessoas sintam que estão fora de controle e são vítimas de sua própria ansiedade. Aprender a ser um observador, em vez de uma vítima de sua própria ansiedade, é um primeiro passo para recuperar o controle. Através do registro, você aprenderá a observar quando, onde e em que circunstâncias seus ataques de pânico e ansiedade ocorrem.

Você aprenderá se seus ataques de pânico ocorrem quando você está sozinho ou com outras pessoas, depois de um dia estressante de trabalho ou nos fins de semana, no meio do dia ou no final do dia; se seus ataques de pânico são desencadeados por sentimentos de empolgação ao assistir a um evento esportivo na televisão, sentir-se superaquecido em uma área de compras lotada, sentir-se sufocado em um chuveiro quente, pensar em coisas horríveis que poderiam acontecer, ou relaxar e não ter mais nada para fazer além de se preocupar com seus medos. Novamente, compreender os fatores que fazem sua ansiedade e pânico aumentarem o ajudará a se sentir mais no controle e menos como uma vítima.

Em segundo lugar, você aprenderá a entender a maneira como vivencia o pânico e a ansiedade, em termos do que pensa, do que sente e do que faz. Essa compreensão é importante porque este programa é projetado especificamente para mudar o pensamento ansioso, os sentimentos ansiosos e os comportamentos ansiosos. Eles não podem ser alterados sem saber exatamente o que são.

Em terceiro lugar, o registro contínuo fornece informações muito mais precisas do que você obteria apenas se perguntasse a si mesmo: "Como tenho me sentido ultimamente?" Se lhe pedissem para descrever a última semana, você poderia julgá-la como sendo "muito ruim", quando, na verdade, pode ter havido várias vezes em que você se sentiu relativamente calmo. Quando a ansiedade está em sua mente com tanta frequência, é fácil esquecer os momentos em que você não estava ansioso. Como você provavelmente pode ver, pensar na semana anterior como "muito ruim" enquanto ignora os momentos "relativamente bons" durante a semana provavelmente o fará se sentir pior e mais ansioso. Na verdade, tais julgamentos negativos sobre como você tem se saído em geral podem contribuir para a ansiedade contínua. Mantendo registros contínuos, você não apenas se sentirá mais no controle, mas também menos ansioso ao reconhecer que seu estado de ânimo flutua e que há momentos em que você se sente menos ansioso do que em outros.

Por fim, o registro ajuda você a avaliar o progresso. Por esse motivo, recomendamos que você registre continuamente durante todo o programa. O registro contínuo permitirá que você aprecie os avanços que fez e ajudará a evitar que ataques de pânico ocasionais ofusquem o progresso que você alcançou.

Vamos rever todos os benefícios do registro contínuo, bem como as razões pelas quais ele é fundamental para este programa:

- Para ajudar você a se sentir mais no controle, identificando quando e onde os ataques de pânico são mais propensos a ocorrer;

- Para identificar as maneiras específicas pelas quais você experimenta a ansiedade, incluindo seus sentimentos físicos, seus pensamentos e seus comportamentos;

- Para ser capaz de avaliar com mais precisão seu nível de ansiedade e pânico; e

- Para avaliar o sucesso de seus esforços para mudar."""],


    'O propósito da ansiedade e do pânico': ["""A ansiedade e o pânico são estados emocionais naturais que são experimentados por todos que fazem parte da experiência de ser humano. A ansiedade é a reação que todos nós temos sempre que pensamos que algo ruim ou ameaçador pode acontecer. Essas coisas ameaçadoras podem incluir ameaças físicas, como a possibilidade de doença, acidente ou morte; ameaças sociais, como a possibilidade de constrangimento, rejeição ou ridicularização; ou ameaças mentais, como a possibilidade de enlouquecer, perder o controle ou perder a faculdade mental. As ameaças podem ser grandes (como a possibilidade de perder a vida) ou pequenas (como a possibilidade de se atrasar para um compromisso). A ansiedade é nossa maneira de nos prepararmos para enfrentar o desafio apresentado por essas ameaças. Ela nos ajuda a nos preparar e nos proteger do que está ameaçando.

A ansiedade não é má em si mesma e pode ser uma força produtiva e motivadora. Anos de pesquisa mostraram que ter alguma ansiedade melhora o desempenho. Ou seja, você se sai melhor no que está fazendo, seja na sala de aula ou no trabalho, quando a ansiedade está presente até certo nível. Imagine não ter absolutamente nenhuma ansiedade em uma entrevista de emprego - você estaria menos motivado para mostrar o seu melhor e enfrentar o desafio de conseguir o emprego. Alguns psicólogos chamaram a ansiedade de "a sombra da inteligência" porque nos motiva a pensar adiante e nos preparar para os desafios que podemos enfrentar. No entanto, a ansiedade pode variar em gravidade, desde um leve desconforto até uma angústia extrema. No extremo, a ansiedade pode interferir no que estamos fazendo. Imagine uma ansiedade extrema em uma entrevista de emprego que leva a uma concentração ruim e gagueira. Alguma ansiedade é útil para o aprendizado e o desempenho, enquanto muito ansiedade pode interferir negativamente nos mesmos processos.  

A ansiedade pode variar em frequência, desde episódios ocasionais até uma sensação aparentemente constante de desconforto. Quando a ansiedade é muito frequente, ela pode interferir na vida cotidiana. Os objetivos deste programa são diminuir a probabilidade de ficar ansioso desnecessariamente e diminuir a intensidade da ansiedade para que você possa funcionar normalmente. No entanto, o objetivo não é eliminar a ansiedade completamente.

Como essa discussão sobre ansiedade se relaciona com o transtorno de pânico? No caso do transtorno de pânico, a ansiedade é experimentada por causa da "ameaça" do pânico. O pânico é considerado ameaçador devido às crenças de que o pânico pode fazer com que você morra, perca o controle ou enlouqueça. Como você verá, essas crenças estão equivocadas porque os ataques de pânico na verdade não são prejudiciais em si."""
],


    'Os componentes da ansiedade': ["""Existem três partes principais nas emoções de ansiedade e pânico: sintomas físicos, pensamentos e comportamentos:

Sintomas Físicos: Esta parte envolve sintomas como batimentos cardíacos rápidos, dificuldade para respirar, estômago nervoso, diarreia, sudorese, tremores, dores de cabeça, dores de estômago, sensação de um nó na garganta, micção frequente e distúrbios visuais (todos esses mais associados a ataques de pânico) e fadiga, inquietação, tensão muscular e sensação de pressão na cabeça (mais associados à ansiedade), entre outros. Os sintomas físicos podem ser agudos, durando um curto período de tempo (como em ataques de pânico), ou podem ser prolongados, durando horas ou dias (como na ansiedade geral). Além disso, os sintomas físicos agudos podem variar de um ataque de pânico para o próximo. Em uma ocasião, você pode notar sintomas intensos de falta de ar, enquanto em outra ocasião pode perceber em vez disso um coração acelerado e pulsante.

Pensamentos: São as crenças, coisas que dizemos a nós mesmos ou imagens de uma iminente catástrofe ou algo terrível prestes a acontecer. Chamamos esses pensamentos de pensamentos negativos. Na maioria das vezes, os pensamentos durante ataques de pânico estão relacionados a catástrofes físicas imediatas (como desmaiar, morrer, ter um ataque cardíaco, tumor cerebral), catástrofes sociais (como zombarias ou ridicularizações) ou catástrofes mentais (como enlouquecer ou perder o controle). Os pensamentos durante a ansiedade se relacionam com coisas ruins que podem acontecer no futuro, como a perda do emprego ou o pior ataque de pânico de todos.

Comportamentos: São as coisas que fazemos, como andar de um lado para o outro, ficar inquieto ou escapar ou evitar lugares onde esperamos que a ansiedade e o pânico ocorram. Um exemplo de fuga é sair de um shopping assim que surgem sentimentos de ansiedade ou pânico. Um exemplo de evitação é não entrar em um shopping devido a preocupações de ter um ataque de pânico uma vez dentro. Outros comportamentos incluem procurar saídas ou maneiras de sair de situações, depender de objetos que fazem você se sentir melhor (esses são os objetos de segurança ou de superstição ) ou procurar ajuda (como em centros médicos).

Esses três componentes frequentemente diferem nos momentos em que você está ansioso em relação aos momentos em que está em pânico. Os pensamentos durante a ansiedade geralmente se relacionam com o futuro (por exemplo, "Meu chefe pode me dar uma avaliação negativa no final do ano" ou "Seria horrível se eu entrasse em pânico na festa de amanhã"), enquanto os pensamentos durante ataques de pânico geralmente se referem à situação imediata (por exemplo, "Vou desmaiar ou morrer agora" ou "Estou enlouquecendo"). Além disso, os comportamentos ansiosos incluem evitar situações ou aumentar a cautela (como planejar totalmente as direções com antecedência para evitar se perder), enquanto os comportamentos durante o pânico têm mais a ver com escapar ou procurar ajuda. Finalmente, os sintomas físicos durante a ansiedade geralmente são de longa duração e envolvem tensão muscular, inquietação e fadiga; em contraste, os sintomas dos ataques de pânico são mais abruptos e tendem a diminuir mais rapidamente do que os sintomas físicos da ansiedade, e incluem palpitações cardíacas, falta de ar e outros sintomas.

""", ['Formulário 3.2: Componentes da Ansiedade','https://drive.google.com/file/d/1c68H6yTWv_DkXAeh6j6C0j9-K8hugJn-/view?usp=drive_link']],
    
    'O ciclo do pânico': ["""Os sintomas físicos, pensamentos e comportamentos contribuem uns para os outros no que é chamado de ciclo negativo. Em outras palavras, eles tendem a se alimentar mutuamente. Por exemplo, pensamentos negativos podem aumentar diretamente os sintomas físicos. Se nos dizemos que algo perigoso está prestes a acontecer (por exemplo, "Estou prestes a ter um ataque cardíaco"), então a tensão física aumentará porque nossos corpos liberam mais adrenalina e operam em ritmo mais rápido sempre que enfrentamos perigo. Por sua vez, um sintoma físico, como um coração acelerado, pode levar a mais pensamentos negativos. Isso é particularmente provável se você acreditar que os sintomas normais de tensão são perigosos (por exemplo, "O fato de que minha frequência cardíaca não diminuiu deve significar que algo está terrivelmente errado"). Comportamentos como agitação, caminhar de um lado para o outro e escapar de uma situação também podem aumentar os níveis de tensão física devido ao esforço físico envolvido.

Mais especificamente, o pensamento de que um coração acelerado é um sinal de doença cardíaca é assustador e produzirá uma frequência cardíaca ainda mais rápida. Por sua vez, uma frequência cardíaca mais rápida pode levar a crenças mais fortes de que algo está terrivelmente errado com o coração. Isso também pode levar a tentativas de obter ajuda médica. Tais pensamentos e comportamentos negativos podem novamente prolongar a aceleração do coração. Em outras palavras, pensamentos negativos levam ao medo, e o medo leva a mais sintomas físicos e comportamentos de fuga que se acumulam em mais pensamentos negativos, e assim por diante. O resultado final é um medo intenso ou pânico. Isso é chamado de ciclo de pânico. Outro exemplo é pensar que a falta de ar significa que você está prestes a sufocar. Esse pensamento causará mais tensão física e mais sintomas de falta de ar, bem como tentativas de respirar mais profundamente, o que por sua vez pode contribuir para a falta de ar (por razões descritas posteriormente), e assim por diante.

Em contraste, pensar que um coração acelerado é inofensivo e não motivo de preocupação interromperá esse ciclo negativo, com o resultado final de que o pânico não ocorre. Da mesma forma, perceber que a falta de ar não é um sinal de sufocamento iminente reduz as chances de um ataque de pânico.

Pense em um ataque de pânico recente e nos sintomas físicos, pensamentos e comportamentos, e como eles contribuíram uns para os outros. O que aconteceu primeiro? Foi um sintoma físico ou um pensamento? O que aconteceu em seguida? Seus sintomas físicos aumentaram, e no que isso o levou a pensar? Como você se comportou? Como suas reações influenciaram seus sintomas físicos?"""],
    
    'Sintomas físicos e o pânico': ["""Pensamentos negativos contribuem para o pânico, principalmente quando relacionados à crença de que os sintomas físicos são prejudiciais. Portanto, é essencial entender com precisão esses sintomas físicos para perceber que não são prejudiciais.

Cientificamente, o medo imediato ou de curto prazo (ou seja, um ataque de pânico) é chamado de resposta de luta ou fuga. Seus efeitos visam a fugir do perigo ou, se isso falhar, lutar para sobreviver. O objetivo principal do pânico é nos proteger do perigo. Mesmo no mundo agitado de hoje, isso é relevante. Imagine-se atravessando uma rua quando um carro se aproxima rapidamente. Se você não sentisse medo, seria atingido. Na realidade, a resposta de luta ou fuga toma conta, e você sai do caminho. O objetivo do pânico é nos proteger, não nos prejudicar.

Quando o perigo é detectado, o cérebro envia mensagens para o sistema nervoso autônomo, que tem dois ramos: o sistema nervoso simpático e o parassimpático. O sistema simpático é responsável por liberar energia e preparar o corpo para a ação (lutar ou fugir), enquanto o parassimpático restaura o estado normal. A ativação do sistema simpático é responsável pela maioria dos sintomas de ataque de pânico.

O sistema simpático é um sistema tudo-ou-nada: quando é ativado, todas as suas partes respondem. Isso pode explicar por que a maioria dos ataques de pânico envolve muitos sintomas físicos, não apenas um ou dois. Além disso, o sistema simpático responde imediatamente, assim que o perigo está próximo. Isso é por que os sintomas físicos dos ataques de pânico podem ocorrer quase instantaneamente, em questão de segundos.

O sistema simpático libera duas substâncias químicas, adrenalina e noradrenalina, das glândulas adrenais nos rins. Essas substâncias são usadas como mensageiros pelo sistema simpático para continuar a atividade, o que pode durar algum tempo. No entanto, a atividade do sistema simpático é interrompida de duas maneiras:

As substâncias químicas adrenalina e noradrenalina são eventualmente destruídas por outras substâncias químicas no corpo.

O sistema nervoso parassimpático, que geralmente tem efeitos opostos ao sistema simpático, é ativado e restaura o estado normal.

Isso significa que o pânico não pode continuar para sempre nem atingir níveis cada vez mais prejudiciais. O sistema parassimpático impede o sistema simpático de se descontrolar.

A adrenalina e a noradrenalina levam algum tempo para serem completamente destruídas. Mesmo depois que o sistema simpático parou de responder, você pode se sentir tenso por algum tempo, pois as substâncias ainda estão em seu sistema. Isso é perfeitamente normal e inofensivo. Na verdade, isso tem um propósito: na natureza, o perigo muitas vezes retorna. É útil para nós permanecermos tensos para que possamos reativar rapidamente a resposta de luta ou fuga se o perigo retornar.

Cada efeito físico do sistema de luta ou fuga tem como objetivo nos preparar para lutar ou fugir, ou seja, nos proteger. Isso afeta nosso coração, fluxo sanguíneo, respiração, suor, pupilas, músculos e sistema digestivo, entre outras partes do corpo.

Efeitos Cardiovasculares:

A atividade no sistema simpático aumenta a frequência cardíaca e a força dos batimentos cardíacas. Isso melhora o fluxo sanguíneo, fornecendo mais oxigênio aos tecidos e removendo resíduos. Isso é vital para a preparação para a ação (lutar ou fugir), pois acelera o fluxo sanguíneo.

O fluxo sanguíneo é redirecionado, afastando-o de onde não é necessário (por meio do estreitamento dos vasos sanguíneos) e direcionando-o para onde é mais necessário (por meio da expansão dos vasos sanguíneos). Por exemplo, o sangue é desviado da pele, dedos e dedos dos pés, para reduzir o risco de lesões. Em vez disso, o sangue vai para os grandes músculos, como as coxas, o coração e os bíceps, que precisam de oxigênio para lutar ou fugir.

Essas mudanças físicas fazem o coração bater rápido e a pele ficar pálida e fria, principalmente ao redor das mãos e dos pés. Isso é uma reação normal em situações de medo ou ansiedade, indicando que o corpo está se preparando para agir.

Efeitos na Respiração:

A respiração fica mais rápida e profunda, pois o corpo precisa de mais oxigênio para lutar ou fugir. Às vezes, a respiração pode ficar desequilibrada e causar sintomas desconfortáveis, como falta de ar, sensação de sufocamento e dor ou aperto no peito.

Além disso, o suprimento de sangue para a cabeça pode ser reduzido. Isso não é perigoso, mas pode causar sintomas desagradáveis, como tontura, visão turva, confusão, sensação de irrealidade e ondas de calor. Esses sintomas físicos podem ser desconfortáveis, mas não indicam algo seriamente errado com você.

Efeitos nas Glândulas Sudoríparas:

A resposta de luta ou fuga aumenta a transpiração para resfriar o corpo e permitir que você continue lutando ou fugindo sem sofrer com o calor. A transpiração é um sintoma comum de ansiedade e pânico.
Outros Efeitos Físicos:

As pupilas dos olhos se dilatam para permitir a entrada de mais luz, ajudando a escanear o ambiente em busca de perigo. Isso faz sentido, já que o pânico e a ansiedade são reações à percepção de ameaça.

A boca fica seca devido à diminuição da salivação, e a atividade do sistema digestivo é reduzida para direcionar a energia para os músculos necessários para lutar ou fugir. Isso pode causar náuseas, sensação de peso no estômago e, às vezes, diarreia.

Muitos grupos musculares se contraem em preparação para a luta ou fuga, resultando em tensão, dores, tremores e tremedeira.

Outro efeito interessante é a liberação de analgésicos naturais pelo cérebro, reduzindo a sensação de dor quando estamos com medo. Isso nos permite continuar lutando ou fugindo, mesmo que estejamos feridos.

Além disso, ocorre a liberação de coagulantes e linfócitos no sangue, que ajudam a fechar feridas e reparar danos nos tecidos. A velocidade de liberação de glóbulos vermelhos também aumenta para transportar mais oxigênio no sangue, e o fígado libera açúcar armazenado para fornecer mais energia aos músculos.

Por fim, como a resposta de luta ou fuga ativa o corpo inteiro, o que requer muita energia, as pessoas geralmente se sentem cansadas e exaustas depois.

Resumindo, as mudanças físicas que causam os sintomas físicos do pânico e da ansiedade são protetoras, destinadas a nos ajudar a escapar ou enfrentar o perigo. Os sintomas são reais, mas não prejudiciais. É importante entender que esses sintomas são uma resposta normal do corpo a situações de estresse e não indicam uma ameaça grave à saúde."""    
],
    
    'Por que ataques de pânico surgem "do nada"?': ["""Após sentir medo várias vezes de sintomas físicos, esse medo pode ocorrer "automaticamente". A qualidade "automática" é típica do que aprendemos em muitos casos. Pense quando você aprendeu a andar de bicicleta ou dirigir um carro. Inicialmente, exigia muita concentração e autoinstrução sobre o que fazer a cada passo do caminho. Gradualmente, tornou-se automático, andar de bicicleta e dirigir sem pensar conscientemente no que se está fazendo. E ainda assim, seus pensamentos automáticos ainda estão orientando o comportamento de como dirigir. A mesma coisa acontece com os pensamentos negativos associados ao pânico e à ansiedade. Com o tempo, eles podem se tornar automáticos, de modo que você não está ciente do que está pensando; no entanto, esses pensamentos ainda influenciam seus sentimentos e comportamentos. Porque você não está ciente de seus pensamentos, pode parecer que o pânico e a ansiedade vêm "do nada" - você simplesmente sente medo e não sabe por quê.

Outro processo automático é chamado condicionamento interoceptivo. Isso significa aprender a ter medo de sintomas físicos devido a experiências negativas anteriores associadas a esses sintomas. Por exemplo, imagine que sempre que você fica doente aparece uma cãibra muscular na perna. Muito em breve, você aprenderia a ter medo de cãibras musculares na perna, antecipando ficar muito doente. A mesma coisa acontece com o pânico; neste caso, no entanto, a cãibra muscular é um sintoma físico que ocorre durante o pânico (como um coração acelerado), e a doença é o terror causado por crenças de que você pode morrer, perder o controle ou enlouquecer. Uma vez que a possibilidade de morte ou alguma outra catástrofe esteja ligada a um coração acelerado, mudanças na frequência cardíaca podem causar medo automático, uma vez que o medo é condicionado. Consequentemente, até mesmo pequenas alterações na frequência cardíaca (causadas, por exemplo, por subir uma escada) que são normais e não o incomodaram antes de você experimentar o pânico podem fazer você ficar com medo. Na verdade, a mudança física pode ser tão sutil que você não está totalmente ciente disso, mas ainda assim isso faz você ter medo. Esta é outra razão pela qual os ataques de pânico às vezes parecem acontecer "do nada" - na verdade, eles são desencadeados por mudanças físicas sutis das quais você não está consciente, mas às quais seu corpo se condicionou a reagir.

Quando julgamentos sobre os sintomas físicos serem perigosos ocorrem automaticamente (ou seja, sem consciência), ou quando o medo é condicionado a sintomas físicos de intensidade mesmo que mínima, de modo que você não está ciente do que está respondendo, então os ataques de pânico parecem ocorrer do nada. Além disso, lembre-se de que nossos sistemas de resposta de emergência de luta ou fuga são projetados de tal forma que respondem instantaneamente (sem pensar conscientemente). Sem essa capacidade de resposta instantânea, não seríamos capazes de sobreviver, porque os perigos às vezes podem nos atingir muito rapidamente. A consequência em termos de ataques de pânico é que crenças e condicionamentos automáticos podem acontecer tão rapidamente que o resultado final - o ataque de pânico - parece acontecer sem tempo para pensar ou reagir. No entanto, na realidade, nosso medo é sempre desencadeado por algo. Ou seja, os sintomas físicos ou os pensamentos negativos sobre os sintomas físicos estão sempre presentes, mesmo que não sejam imediatamente óbvios.

Isso também é verdade para ataques de pânico que ocorrem a partir de um estado relaxado e para ataques de pânico que o acordam de um sono profundo (ou seja, ataques de pânico noturnos). Durante o relaxamento, os sentimentos físicos frequentemente são diferentes do normal, às vezes resultando em sensações de flutuação ou estar em transe. Se você tem medo de sensações físicas diferentes do normal, então os sentimentos físicos que você tem durante o relaxamento podem desencadear um ataque de pânico. Ataques de pânico noturnos são experimentados por cerca de metade das pessoas que sofrem de transtorno do pânico, e cerca de 25% têm ataques de pânico repetidos durante o sono.

Você pode perguntar: "Como os ataques de pânico noturnos podem ser desencadeados por sensações físicas"? Primeiro, é normal ter mudanças nos ritmos físicos durante o sono. Por exemplo, as taxas cardíacas e as taxas de respiração aumentam e diminuem em momentos diferentes durante a noite. Em segundo lugar, temos a capacidade de responder a eventos significativos durante o sono. Pense na mãe que acorda em resposta ao menor som de seu bebê recém-nascido, enquanto dorme com outros sons mais altos, como caminhões passando em uma rodovia próxima. Outro exemplo seriam os soldados em combate que têm a capacidade de dormir com o som de aviões aliados, mas acordam com o som de aviões inimigos. Assim, se as mudanças físicas forem significativas (ou seja, se forem assustadoras), é compreensível que as mudanças físicas que normalmente ocorrem durante o sono possam fazer alguém acordar em um ataque de pânico, da mesma forma que os ataques de pânico ocorrem durante o dia. Isso é especialmente provável de acontecer se as mudanças físicas ocorrerem em um momento durante o sono em que é mais fácil acordar. Por exemplo, é muito difícil acordar de um sono profundo e do sono com movimento rápido dos olhos (REM) quando ocorrem sonhos, mas é mais fácil acordar das Etapas 2 e 3 do sono, que é quando a maioria dos ataques de pânico noturnos ocorre. É por isso que não são sonhos ou pesadelos que causam ataques de pânico noturnos, um equívoco comum."""
],
    'Formulário de Situações típicas de agorafobia': ["""Condições: Aqui estão algumas das condições a serem consideradas que podem influenciar o nível de ansiedade que você experimenta em cada situação de agorafobia. É muito importante incluir as condições que fazem com que você se sinta mais ansioso. Por exemplo, se você sempre se sente mais ansioso quando está sozinho, será essencial incluir situações em sua hierarquia nas quais você esteja sozinho.
Distância de Casa
Por exemplo, dirigir na autoestrada pode ser dividido em várias tarefas diferentes, dependendo da distância de sua casa (10 minutos de casa versus 1 hora de casa). Essas podem ser diferentes etapas em sua hierarquia, e será importante incluir distâncias maiores de casa em sua hierarquia se você normalmente fica mais ansioso quanto mais longe estiver de casa.
Proximidade de uma Saída ou Facilidade de Fuga
Ir ao cinema pode ser mais ou menos provocador de ansiedade, dependendo de quão longe no meio da fileira você está sentado durante o filme. Sentar no meio da fileira pode ser muito mais provocador de ansiedade do que sentar na fileira do corredor, se for importante para você ser capaz de sair de onde estiver. Da mesma forma, dirigir na autoestrada pode ser mais fácil ou mais difícil dependendo das distâncias entre as saídas e entradas. Se for o caso, certifique-se de eventualmente enfrentar situações em que as saídas ou a fuga sejam muito difíceis, mesmo que você comece com situações das quais seja fácil sair.
Hora do Dia
Fazer compras no supermercado pode ser mais fácil ou mais difícil, dependendo se você faz as compras de manhã, à tarde ou à noite. Por exemplo, às vezes as pessoas ficam mais ansiosas à tarde ou à noite porque se sentem mais cansadas e menos capazes de lidar com o pânico. Se isso fizer diferença para você, adicione itens à sua hierarquia que incluam os horários mais difíceis do dia.
Número de Pessoas
Se a situação estiver lotada ou não pode influenciar o nível de ansiedade. Portanto, fazer compras durante o horário de pico ou dirigir durante o horário de rush pode ser diferente de fazer compras ou dirigir quando as condições são muito menos lotadas. Se isso for importante para você, inclua itens em sua hierarquia que envolvam horários lotados.
Acompanhado ou Sozinho
Claro, a presença de amigos ou familiares muitas vezes faz uma grande diferença. Contar com certas outras pessoas é uma forma de confiar em um sinal de segurança (como descrito no capítulo 1). Se você se sente menos ansioso quando está com certas pessoas, pode começar a enfrentar seu medo de situações de agorafobia com a ajuda delas, mas será essencial enfrentar as mesmas situações sem essas pessoas eventualmente. Portanto, sua hierarquia deve incluir enfrentar situações sem a ajuda de outros, se ficar sozinho o torna mais ansioso.""", 
['Formulário de Situações típicas de agorafobia', 'https://forms.gle/2kiR5Yn4Qdo4wjRy9']],
'Comportamentos de Segurança e Distrações' : [ """Alguns estilos de comportamento podem reduzir a ansiedade a curto prazo, mas são inúteis a longo prazo porque interferem no aprendizado de domínio da situação. Em particular, estamos nos referindo a exemplos de "se agarrar à vida", como se a situação enfrentada fosse realmente perigosa. Exemplos incluem permanecer próximo a estruturas (como edifícios ou corrimãos) para proporcionar uma sensação de apoio físico. Isso é especialmente verdadeiro para pessoas que têm medo de cair. No entanto, permanecer próximo a estruturas fortalece a crença equivocada de que a queda é provável quando se está "lá fora".

Outro exemplo é segurar firmemente o volante com medo de perder o controle. Na realidade, seria bastante seguro relaxar um pouco as mãos. Procurar saídas é outro comportamento de segurança. Por exemplo, você pode se pegar procurando placas de saída ao sair em uma grande boate ou olhando repetidamente para verificar a visibilidade da placa de saída ao fazer compras em um shopping. Novamente, a busca por uma saída se baseia na crença equivocada de que algum perigo pode ocorrer se a situação for inescapável. As placas de saída também podem funcionar como sinais de segurança.
Como mencionado anteriormente, a distração é outro método paliativo que contribui para a ansiedade a longo prazo. Você deve eventualmente enfrentar suas situações de agorafobia sem a ajuda da distração. A distração pode ser óbvia ou sutil, mas, em todos os casos, é uma forma de evitar a situação. Uma técnica de distração muito comum é desviar o olhar do objeto que causa medo. Por exemplo, enquanto você pode enfrentar o medo de altura subindo para o 10º andar de um edifício, pode estar evitando-o ao mesmo tempo por se recusar a olhar pela janela. Da mesma forma, você pode enfrentar seu medo de elevadores usando-os, mas ao mesmo tempo ao manter os olhos fechados durante o trajeto é uma estratégia de evitação.

Métodos mais sutis de distração incluem usar sua imaginação para fingir estar em outro lugar ou jogar jogos de números ou palavras até sair do túnel, ou cruzar a ponte, e assim por diante. Outros métodos mais perigosos e raros de distração incluem infligir dor a si mesmo ou dirigir em alta velocidade sob a suposição de que a dor ou o susto superará e eliminará o pânico. Claro, no final, os últimos métodos de distração são muito mais perigosos do que um ataque de pânico.
Os melhores resultados vêm de um foco objetivo em suas reações a uma determinada situação e na própria situação. O foco objetivo em si mesmo é exemplificado pelo tipo de auto-afirmação a seguir: "Estou no elevador, consigo sentir ele se movendo, consigo ver as portas, o teto e o chão, sinto meu coração batendo, e minha ansiedade está moderada." O foco objetivo em si mesmo difere do autoconhecimento subjetivo, que é exemplificado por uma afirmação como "me sinto terrível, vou desmoronar, não consigo suportar, tenho que sair daqui." O foco subjetivo é provavelmente o estilo com o qual você naturalmente se envolve, uma vez que faz parte de estar ansioso e com medo.

Com frequência, as tentativas de se manter distraído alternam com momentos breves, mas negativos, de foco subjetivo em si mesmo. Por exemplo, usar jogos de contagem ou imaginação para se manter distraído é provável que seja intercalado com o monitoramento momentâneo do corpo ou questionamentos sobre o quão mal você está se sentindo em determinado momento. Essa combinação de distração e foco subjetivo provavelmente contribuirá para a ansiedade contínua. Seu objetivo é substituir esse estilo por um foco objetivo e plena consciência do que está acontecendo.
Um objetivo deste programa é ajudá-lo a eliminar todos os seus comportamentos de segurança e distrações.""" , ['Comportamentos de Segurança e Distrações', 'https://forms.gle/CqmnwrS3pbfLvnPW8']],
'Respiração Normal, Ansiedade e Hiperventilação': ["""Essa breve explicação sobre a mecânica da respiração e os sintomas da hiperventilação ajudará a corrigir a crença equivocada de que os sintomas da hiperventilação são prejudiciais.

Nosso corpo precisa de oxigênio para sobreviver. Sempre que inalamos, o oxigênio entra em nossos pulmões, onde é captado pela hemoglobina (a substância "cola de oxigênio" no sangue). A hemoglobina transporta o oxigênio por todo o corpo, onde é liberado para uso pelas células do corpo. As células utilizam o oxigênio em suas reações energéticas. Após utilizar o oxigênio, o dióxido de carbono é liberado de volta para o sangue, onde é transportado para os pulmões e, finalmente, expelido.

Manter o equilíbrio entre oxigênio e dióxido de carbono é fundamental e é regulado principalmente pela taxa e profundidade adequadas da respiração. É evidente que a respiração "em excesso" aumenta os níveis de oxigênio (apenas no sangue) e diminui os níveis de dióxido de carbono, enquanto a respiração insuficiente reduz os níveis de oxigênio e aumenta os níveis de dióxido de carbono. A taxa apropriada de respiração em repouso geralmente varia entre 10 e 14 respirações por minuto.

A hiperventilação é definida como uma taxa e profundidade da respiração que são excessivas para as necessidades do corpo em um momento específico. Naturalmente, se a necessidade de oxigênio e a produção de dióxido de carbono aumentam (como durante o exercício), a respiração deve aumentar adequadamente. Por outro lado, se a necessidade de oxigênio e a produção de dióxido de carbono diminuem (como durante o relaxamento), a respiração deve diminuir apropriadamente.

A ansiedade e o medo nos fazem aumentar a respiração porque nossos músculos precisam de mais oxigênio para lutar ou fugir do perigo. Se o oxigênio extra não for utilizado na mesma taxa em que é inalado (como seria o caso se não houvesse corrida ou luta real acontecendo), ocorre o estado de hiperventilação, ou seja, respiração em excesso.

O efeito mais importante da hiperventilação é produzir uma queda proporcional no dióxido de carbono (significando que a quantidade de dióxido de carbono é baixa em proporção à quantidade de oxigênio). Nossos sistemas nervosos e químicos são muito mais sensíveis aos níveis de dióxido de carbono do que aos níveis de oxigênio no sangue. Uma queda proporcional no dióxido de carbono, por sua vez, produz uma diminuição no teor de ácido do sangue, levando ao que é conhecido como sangue alcalino. São esses dois efeitos - uma diminuição proporcional nos níveis de dióxido de carbono no sangue e um aumento na alcalinidade do sangue - que são responsáveis pela maioria das alterações físicas que ocorrem durante a hiperventilação.

Uma das mudanças mais importantes produzidas pela hiperventilação é a constrição ou estreitamento de certos vasos sanguíneos em todo o corpo. Juntamente com esse estreitamento dos vasos sanguíneos, a hemoglobina aumenta sua "aderência" ao oxigênio. Não apenas menos sangue chega a certas áreas do corpo, mas o oxigênio transportado por esse sangue tem menos probabilidade de ser liberado nos tecidos. Embora a hiperventilação signifique que estamos absorvendo mais oxigênio do que o necessário, um pouco menos de oxigênio realmente chega a certas áreas do cérebro e do corpo. É importante lembrar que as reduções no oxigênio são leves e totalmente inofensivas.

No entanto, a fisiologia da hiperventilação produz sintomas definitos e, às vezes, intensos. Primeiro, os sintomas incluem tontura, sensação de cabeça leve, confusão e sentimentos de irrealidade. Segundo, os sintomas incluem aumento da frequência cardíaca (para bombear mais sangue pelo corpo); dormência e formigamento nas extremidades; mãos frias e úmidas; e, às vezes, rigidez dos músculos. Além disso, a hiperventilação pode causar uma sensação de falta de ar, que às vezes se estende a uma sensação de sufocação, de modo que realmente parece que não há ar suficiente. Na realidade, há bastante ar. Você pode ter notado muitos desses sintomas se já fez algum exercício de hiperventilação antes.

A hiperventilação também causa outros efeitos. Primeiro, o ato de hiperventilar é um trabalho físico árduo. Isso pode fazer você se sentir quente, corado e suado, e após períodos prolongados, frequentemente causará cansaço e exaustão. Além disso, as pessoas que hiperventilam frequentemente respiram mais pelo peito do que pelo diafragma (o músculo sob as costelas). Quando os músculos do peito são usados predominantemente, eles ficam cansados e sensíveis devido ao uso excessivo. Isso às vezes causa aperto no peito ou até dores no peito graves. Finalmente, muitas pessoas que hiperventilam têm o hábito de suspirar ou bocejar. Infelizmente, esses hábitos contribuem para o problema, porque suspirar e bocejar causam a eliminação rápida de grandes quantidades de dióxido de carbono do sistema, reduzindo a quantidade proporcional de dióxido de carbono no sangue. 
A hiperventilação nem sempre é óbvia. Por exemplo, a respiração excessiva leve pode ocorrer ao longo de longos períodos de tempo sem sinais óbvios de hiperventilação. Isso ocorre porque o corpo trabalha para equilibrar a diminuição do dióxido de carbono, a fim de manter um nível normal de acidez sanguínea. Assim, os sintomas não estão sempre presentes. No entanto, como os níveis de dióxido de carbono permanecem baixos, o corpo perde sua capacidade de lidar com as mudanças na respiração. Consequentemente, mesmo uma leve alteração na respiração (por exemplo, um bocejo ou subir um lance de escadas) pode ser suficiente para causar repentinamente o aparecimento dos sintomas. Isso pode explicar a natureza súbita de muitos ataques de pânico - uma pequena mudança na respiração em alguém que tem uma tendência geral a hiperventilar, mesmo que apenas levemente, causa hiperventilação aguda.

Provavelmente, o ponto mais importante a ser destacado sobre a hiperventilação é que ela não é perigosa."""],

'Respiração diafragmática': ["""Com este exercício você aprenderá a diferenciar a respiração diafragmática da respiração "profunda". As pessoas frequentemente dizem "apenas respire fundo" como uma forma de lidar com ataques de pânico, e isso normalmente significa tomar uma grande respiração (uma inalação enorme de ar). No entanto, tomar uma grande respiração é contraproducente. Quando falamos de respiração diafragmática, estamos nos referindo a redirecionar o foco para longe do peito em direção ao abdômen, mantendo ao mesmo tempo uma respiração de tamanho normal.

O objetivo deste exercício é aprender um método de regular sua respiração que o ajudará a lidar diretamente com os sintomas físicos e as situações que atualmente o deixam ansioso. Essa habilidade de respiração não é projetada para controlar ou prevenir sentimentos de medo e ansiedade; em vez disso, destina-se a ajudá-lo a enfrentar os sentimentos de medo e ansiedade e as situações em que eles surgem.

O exercício envolve um componente de respiração, no qual você aprende a desacelerar sua respiração e a usar mais o músculo do diafragma do que os músculos do peito, e um componente de meditação. Meditação significa focar sua atenção no exercício de respiração. Como todas as habilidades, aprender a meditar requer prática.

O seguinte exercício deve ser praticado pelo menos duas vezes ao dia, por pelo menos 10 minutos cada vez. No início, o exercício pode ser difícil, mas ficará mais fácil quanto mais você o praticar.

Passo 1

O primeiro passo é se concentrar em fazer respirações até a parte inferior do seu estômago (ou, mais precisamente, até os músculos do diafragma).

■ Deve haver uma expansão (aumento) do estômago toda vez que você inspirar. O estômago é puxado de volta toda vez que você expirar.

■ Se você tiver dificuldade em levar o ar até o seu estômago, coloque uma mão no peito e a outra no estômago, com o dedo mínimo cerca de 2,5 centímetros acima do umbigo. Conforme você inspira e expira, apenas a mão no estômago deve se mover. Se você estiver fazendo o exercício corretamente, não deve haver muita movimentação da mão no peito. Se você normalmente respira pelo peito, isso pode parecer artificial e causar sensações de falta de ar. Isso é uma resposta natural. Apenas lembre-se de que você está recebendo oxigênio suficiente e que as sensações de falta de ar diminuirão à medida que você praticar.

Passo 2

O segundo passo é respirar quantidades normais de ar. Pânico e ansiedade frequentemente produzem a sensação de não ter ar suficiente e o desejo de tomar grandes respirações. No entanto, tomar uma grande respiração levará a uma queda desproporcional na quantidade de dióxido de carbono no sangue, levando a mais hiperventilação. Portanto, não faça grandes respirações; faça uma respiração de tamanho médio ou até mais superficial.

■ Nesta fase, respire na sua taxa normal - não tente diminuir a respiração. Vamos trabalhar na redução da respiração mais tarde.

■ Além disso, mantenha sua respiração suave. Não respire fundo de uma vez e solte todo o ar de uma só vez. Ao expirar, pense no ar como escorrendo e escapando pelo nariz ou pela boca, em vez de sair subitamente. Não importa se você respira pelo nariz ou pela boca, desde que respire suavemente.

Passo 3

O terceiro passo envolve a meditação. Você contará sempre que inspirar e pensará na palavra "relaxar" ao expirar.

■ Ou seja, quando você inspirar, pense "um" para si mesmo; e, ao expirar, pense na palavra "relaxar". Pense "dois" na sua próxima inspiração e pense "relaxar" na expiração. Pense "três" na próxima inspiração e pense "relaxar" na expiração. Continue fazendo isso até contar cerca de "10" e depois volte ao "um".

■ Concentre-se apenas na sua respiração e nas palavras. Isso pode ser muito difícil, e você pode nunca conseguir fazer isso perfeitamente. Você pode não passar do primeiro número sem que outros pensamentos entrem em sua mente. Isso é natural. Quando isso acontecer, não fique com raiva ou desista. Apenas permita que os pensamentos passem pela sua mente e, em seguida, traga sua atenção de volta para a respiração, os números e as palavras.

Pratique duas vezes ao dia (ou mais, se desejar), por cerca de 10 minutos cada vez, em situações relaxantes, como em um local tranquilo em casa onde você não será perturbado.

Essa nova forma de respiração pode parecer estranha no início e causar sensações de falta de ar. Isso é natural. Apenas lembre-se de que você está recebendo oxigênio suficiente e que ficará mais fácil quanto mais você praticar.

Por enquanto, não utilize esse novo tipo de respiração calma nos momentos de ansiedade, pois tentar usar uma estratégia que está apenas parcialmente desenvolvida pode ser mais frustrante e gerar mais ansiedade do que não tentar usá-la de forma alguma. Seria como ensinar uma técnica de lidar com emergências subaquáticas a mergulhadores uma única vez e depois esperar que eles usem a habilidade com sucesso em uma emergência real debaixo d'água. Em vez disso, os mergulhadores devem praticar o procedimento de emergência em terra repetidamente antes de usá-lo debaixo d'água. Portanto, por enquanto, os exercícios de respiração devem ser feitos apenas em um ambiente tranquilo e confortável. Uma vez que você tenha adquirido habilidade no exercício básico de respiração calma, então aplicaremos isso como uma habilidade de enfrentamento para a ansiedade.

Após cada prática, registre seus níveis de concentração na respiração e na contagem, bem como o sucesso com o qual você consegue usar o músculo do diafragma, utilizando o formulário específico.""",
['Formulário 6.1: Seu Registro de Habilidades de Respiração', 'https://docs.google.com/document/d/1Of-VP9f6qSVZmpyot9mbyzowbBEmLPJvi7iweFKMDZg/edit?usp=share_link']],
    'A relação entre pensamento e emoção': ["""Pensamentos Influenciam Emoções

Imagine uma amiga se aproximando de você. Em vez de sorrir e dizer "olá", ela passa direto por você sem nem mesmo lhe cumprimentar. O que você pode pensar sobre isso? Se você pensar que sua amiga está com raiva ou chateada com você, você pode sentir ansiedade ou tristeza. Se você pensar que ela está estressada com alguma outra coisa e nem sequer percebeu você, então você pode sentir muito pouca emoção ou, talvez, até sentir compaixão por ela. Claro, isso é relevante para o transtorno do pânico, pois a maneira como você pensa sobre os sintomas físicos influenciará como você se sente em relação a eles.

Emoções Influenciam Pensamentos

Emoções negativas causam mais pensamentos negativos: Sentir medo aumenta a probabilidade de ter pensamentos negativos. Isso ocorre porque o principal efeito do sistema de luta ou fuga é nos alertar para a possibilidade de perigo. No entanto, às vezes uma ameaça óbvia não pode ser encontrada. É difícil para nós aceitar não ter uma explicação para sentimentos de pânico ou para experimentar qualquer emoção forte. Quando as pessoas não conseguem encontrar uma explicação óbvia para seus sentimentos, geralmente inventam uma, e isso frequentemente envolve direcionar sua busca para si mesmas. Em outras palavras, "Se nada lá fora está me fazendo sentir medo, então deve haver algo errado comigo." Nesse caso, o cérebro inventa uma explicação, como "Eu devo estar morrendo, perdendo o controle ou enlouquecendo." O objetivo do sistema de luta ou fuga é proteger o organismo, não prejudicá-lo - é o nosso mecanismo de sobrevivência. O fato de a ansiedade produzir mais pensamentos negativos ajuda a explicar por que, quando estão calmas, muitas pessoas reconhecem que seus ataques de pânico não as prejudicarão; no entanto, quando estão no meio de um ataque de pânico, essas mesmas pessoas estão convencidas de que seus ataques de pânico são prejudiciais.

Ciclo de Emoções e Pensamentos

Neste ponto, você pode pensar: "Não me digo nada quando estou em pânico; isso simplesmente acontece do nada." Há uma dimensão de consciência em nosso pensamento. Ou seja, às vezes estamos totalmente conscientes de nossos pensamentos, mas outras vezes, nossos pensamentos são tão automáticos que nem sabemos o que estamos pensando. Como exemplo disso, pense em dirigir um carro. Há muitos pensamentos que passam quando você sai de um local de estacionamento (por exemplo, colocar o pé no acelerador, colocar o pé no freio, virar o volante desta maneira, olhar por cima do ombro, sair lentamente, e assim por diante). No entanto, provavelmente você não está ciente desses pensamentos. Os pensamentos tendem a se tornar automáticos quanto mais frequentemente pensamos neles. Portanto, por exemplo, se você acredita há muito tempo que ataques de pânico causam doenças cardíacas, um leve espasmo no peito pode desencadear um ataque de pânico sem que você perceba que, ao notar o espasmo, você estava pensando que poderia estar tendo um ataque cardíaco - o pensamento se torna automático. No entanto, com uma observação cuidadosa de si mesmo, geralmente podemos aprender a reconhecer nossos pensamentos automáticos. Para cada situação de agorafobia, pergunte a si mesmo: "O que acontecerá se eu entrar e permanecer nessa situação?" Para cada ataque de pânico, pergunte a si mesmo: "O que eu achei que poderia acontecer?"
Agora é hora de ser o mais detalhado possível. Ou seja, em vez de dizer "Pensei que poderia entrar em pânico", liste as diferentes possibilidades negativas que passaram por sua mente, mesmo que tenha sido apenas por um segundo, como "Se eu entrar em pânico, posso morrer de um ataque cardíaco." Se suas descrições de seus pensamentos forem gerais, como "Me senti horrível" ou "Vou me sentir ansioso", pergunte a si mesmo: "Por que foi tão terrível? O que eu achava que poderia acontecer?" Ou, se o seu pensamento foi: "Posso perder o controle", pergunte a si mesmo: "O que poderia ter acontecido se eu perdesse o controle?" Em outras palavras, seja mais específico do que simplesmente afirmar que você tem medo de entrar em pânico, ou medo de ficar ansioso em uma situação, ou que isso fará você se sentir mal ou horrível. O pânico e a ansiedade são estados emocionais da mesma forma que a raiva, a excitação e a tristeza são estados emocionais. Eles não são inerentemente perigosos. Quando você diz que tem medo de ter um ataque de pânico, significa que o pânico sinaliza algo de ruim acontecendo com você, como lesões físicas (ataque cardíaco, derrame, desmaio), pensar estar enlouquecendo, crer estar perdendo o controle, morrendo ou mesmo achar estar sendo excluído e humilhado socialmente. Estes são os pensamentos negativos - as chamadas catástrofes - que contribuem para o ciclo de pânico.
Da mesma forma, se seu pensamento inicial é que você tem medo de ficar preso ou que será muito difícil sair de uma situação, pense mais nos motivos pelos quais isso o preocupa. Lembre-se de que a necessidade de escapar de uma situação é relevante apenas na medida em que você acha que algo ruim acontecerá se você for forçado a permanecer na situação. Pode ajudar a pensar em si mesmo como estando literalmente preso em sua situação temida (por exemplo, imagine-se preso em um elevador ou em uma viagem de avião muito longa) e pergunte a si mesmo o que o motiva a querer sair. Por exemplo, o medo de ficar preso pode se basear em pensamentos de perder o controle gritando e machucando pessoas para sair.
Aqui está um exemplo de uma discussão entre um terapeuta e um cliente com transtorno do pânico. O terapeuta está ajudando o cliente a identificar os pensamentos negativos com o máximo de detalhes possível.

terapeuta: O que você quer dizer quando diz que a sensação de coração acelerado é horrível? O que há de horrível nisso?

Carlos: Bem, me faz sentir muito assustado.

Terapeuta: Do que você tem medo?

Carlos: Isso me faz preocupar com algo saindo errado fisicamente.

Terapeuta: O que você acha que poderia acontecer?

Carlos: Talvez meu coração continue batendo mais e mais rápido, e eventualmente, ele vai parar.

Terapeuta: E então?

Carlos: Bem, então eu vou morrer.

Terapeuta: Ok, então agora identificamos precisamente o que você acha que poderia acontecer. E quanto aos seus medos de perder totalmente o controle? O que você quer dizer com isso?

Carlos: É difícil de descrever. Acho que na verdade não sei o que isso significa. Eu só me sinto fora de controle.

Terapeuta: O que você acha que poderia acontecer se você estivesse totalmente fora de controle?

Carlos: Que eu não poderia parar o jeito que estava me sentindo.

Terapeuta: E o que aconteceria se você não conseguisse parar esse sentimento?

Carlos: Bem, o sentimento ficaria tão intenso que eu não seria capaz de funcionar mais. Eu seria apenas um desastre.

Terapeuta: E então?

Carlos: Isso seria o fim da minha vida. Eu passaria o resto da minha vida sem fazer nada.

Use este tipo de abordagem para descobrir seus pensamentos para os ataques de pânico que tiver registrado.""",
['Formulário de pensamentos negativos', 'https://docs.google.com/document/d/15aXNmpv9yF0aT5dbwbyze02Z6ksikrbGZ6jbyBkR3hE/edit?usp=sharing']],

}