texts_choice = {
    
    'Razões para fazer registros': ["""Existem muitas razões pelas quais é importante manter registros regulares e contínuos de sua ansiedade. Em primeiro lugar, ataques de pânico, especialmente aqueles que parecem ocorrer sem motivo aparente, fazem com que as pessoas sintam que estão fora de controle e são vítimas de sua própria ansiedade. Aprender a ser um observador, em vez de uma vítima de sua própria ansiedade, é um primeiro passo para recuperar o controle. Através do registro, você aprenderá a observar quando, onde e em que circunstâncias seus ataques de pânico e ansiedade ocorrem.

Você aprenderá se seus ataques de pânico ocorrem quando você está sozinho ou com outras pessoas, depois de um dia estressante de trabalho ou nos fins de semana, no meio do dia ou no final do dia; se seus ataques de pânico são desencadeados por sentimentos de empolgação ao assistir a um evento esportivo na televisão, sentir-se superaquecido em uma área de compras lotada, sentir-se sufocado em um chuveiro quente, pensar em coisas horríveis que poderiam acontecer, ou relaxar e não ter mais nada para fazer além de se preocupar com seus medos. Novamente, compreender os fatores que fazem sua ansiedade e pânico aumentarem o ajudará a se sentir mais no controle e menos como uma vítima.

Em segundo lugar, você aprenderá a entender a maneira como vivencia o pânico e a ansiedade, em termos do que pensa, do que sente e do que faz. Essa compreensão é importante porque este programa é projetado especificamente para mudar o pensamento ansioso, os sentimentos ansiosos e os comportamentos ansiosos. Eles não podem ser alterados sem saber exatamente o que são.

Em terceiro lugar, o registro contínuo fornece informações muito mais precisas do que você obteria apenas se perguntasse a si mesmo: "Como tenho me sentido ultimamente?" Se lhe pedissem para descrever a última semana, você poderia julgá-la como sendo "muito ruim", quando, na verdade, pode ter havido várias vezes em que você se sentiu relativamente calmo. Quando a ansiedade está em sua mente com tanta frequência, é fácil esquecer os momentos em que você não estava ansioso. Como você provavelmente pode ver, pensar na semana anterior como "muito ruim" enquanto ignora os momentos "relativamente bons" durante a semana provavelmente o fará se sentir pior e mais ansioso. Na verdade, tais julgamentos negativos sobre como você tem se saído em geral podem contribuir para a ansiedade contínua. Mantendo registros contínuos, você não apenas se sentirá mais no controle, mas também menos ansioso ao reconhecer que seu estado de ânimo flutua e que há momentos em que você se sente menos ansioso do que em outros.

Por fim, o registro ajuda você a avaliar o progresso. Por esse motivo, recomendamos que você registre continuamente durante todo o programa. O registro contínuo permitirá que você aprecie os avanços que fez e ajudará a evitar que ataques de pânico ocasionais ofusquem o progresso que você alcançou.

Vamos rever todos os benefícios do registro contínuo, bem como as razões pelas quais ele é fundamental para este programa:

- Para ajudar você a se sentir mais no controle, identificando quando e onde os ataques de pânico são mais propensos a ocorrer;

- Para identificar as maneiras específicas pelas quais você experimenta a ansiedade, incluindo seus sentimentos físicos, seus pensamentos e seus comportamentos;

- Para ser capaz de avaliar com mais precisão seu nível de ansiedade e pânico; e

- Para avaliar o sucesso de seus esforços para mudar."""],


    'O propósito da ansiedade e do pânico': ["""A ansiedade e o pânico são estados emocionais naturais que são experimentados por todos fazem parte da experiência de ser humano. A ansiedade é a reação que todos nós temos sempre que pensamos que algo ruim ou ameaçador pode acontecer. Essas coisas ameaçadoras podem incluir ameaças físicas, como a possibilidade de doença, acidente ou morte; ameaças sociais, como a possibilidade de constrangimento, rejeição ou ridicularização; ou ameaças mentais, como a possibilidade de enlouquecer, perder o controle ou perder a faculdade mental. As ameaças podem ser grandes (como a possibilidade de perder a vida) ou pequenas (como a possibilidade de se atrasar para um compromisso). A ansiedade é nossa maneira de nos prepararmos para enfrentar o desafio apresentado por essas ameaças. Ela nos ajuda a nos preparar e nos proteger do que está ameaçando.

A ansiedade não é má em si mesma e pode ser uma força produtiva e motivadora. Anos de pesquisa mostraram que ter alguma ansiedade melhora o desempenho. Ou seja, você se sai melhor no que está fazendo, seja na sala de aula ou no trabalho, quando a ansiedade está presente até certo nível. Imagine não ter absolutamente nenhuma ansiedade em uma entrevista de emprego - você estaria menos motivado para mostrar o seu melhor e enfrentar o desafio de conseguir o emprego. Alguns psicólogos chamaram a ansiedade de "a sombra da inteligência" porque nos motiva a pensar adiante e nos preparar para os desafios que podemos enfrentar. No entanto, a ansiedade pode variar em gravidade, desde um leve desconforto até uma angústia extrema. No extremo, a ansiedade pode interferir no que estamos fazendo. Imagine uma ansiedade extrema em uma entrevista de emprego que leva a uma concentração ruim e gagueira. Alguma ansiedade é útil para o aprendizado e o desempenho, enquanto muito ansiedade pode interferir negativamente nos mesmos processos.  

A ansiedade pode variar em frequência, desde episódios ocasionais até uma sensação aparentemente constante de desconforto. Quando a ansiedade é muito frequente, ela pode interferir na vida cotidiana. Os objetivos deste programa são diminuir a probabilidade de ficar ansioso desnecessariamente e diminuir a intensidade da ansiedade para que você possa funcionar normalmente. No entanto, o objetivo não é eliminar a ansiedade completamente.

Como essa discussão sobre ansiedade se relaciona com o transtorno de pânico? No caso do transtorno de pânico, a ansiedade é experimentada por causa da "ameaça" do pânico. O pânico é considerado ameaçador devido às crenças de que o pânico pode fazer com que você morra, perca o controle ou enlouqueça. Como você verá, essas crenças estão equivocadas porque os ataques de pânico na verdade não são prejudiciais em si."""
],

    'Os componentes da ansiedade': ["""Existem três partes principais nas emoções de ansiedade e pânico: sintomas físicos, pensamentos e comportamentos:

Sintomas Físicos: Esta parte envolve sintomas como batimentos cardíacos rápidos, dificuldade para respirar, estômago nervoso, diarreia, sudorese, tremores, dores de cabeça, dores de estômago, sensação de um nó na garganta, micção frequente e distúrbios visuais (todos esses mais associados a ataques de pânico) e fadiga, inquietação, tensão muscular e sensação de pressão na cabeça (mais associados à ansiedade), entre outros. Os sintomas físicos podem ser agudos, durando um curto período de tempo (como em ataques de pânico), ou podem ser prolongados, durando horas ou dias (como na ansiedade geral). Além disso, os sintomas físicos agudos podem variar de um ataque de pânico para o próximo. Em uma ocasião, você pode notar sintomas intensos de falta de ar, enquanto em outra ocasião pode perceber em vez disso um coração acelerado e pulsante.

Pensamentos: São as crenças, coisas que dizemos a nós mesmos ou imagens de uma iminente catástrofe ou algo terrível prestes a acontecer. Chamamos esses pensamentos de pensamentos negativos. Na maioria das vezes, os pensamentos durante ataques de pânico estão relacionados a catástrofes físicas imediatas (como desmaiar, morrer, ter um ataque cardíaco, tumor cerebral), catástrofes sociais (como zombarias ou ridicularizações) ou catástrofes mentais (como enlouquecer ou perder o controle). Os pensamentos durante a ansiedade se relacionam com coisas ruins que podem acontecer no futuro, como a perda do emprego ou o pior ataque de pânico de todos.

Comportamentos: São as coisas que fazemos, como andar de um lado para o outro, ficar inquieto ou escapar ou evitar lugares onde esperamos que a ansiedade e o pânico ocorram. Um exemplo de fuga é sair de um shopping assim que surgem sentimentos de ansiedade ou pânico. Um exemplo de evitação é não entrar em um shopping devido a preocupações de ter um ataque de pânico uma vez dentro. Outros comportamentos incluem procurar saídas ou maneiras de sair de situações, depender de objetos que fazem você se sentir melhor (esses são os objetos de segurança ou de superstição ) ou procurar ajuda (como em centros médicos).

Esses três componentes frequentemente diferem nos momentos em que você está ansioso em relação aos momentos em que está em pânico. Os pensamentos durante a ansiedade geralmente se relacionam com o futuro (por exemplo, "Meu chefe pode me dar uma avaliação negativa no final do ano" ou "Seria horrível se eu entrasse em pânico na festa de amanhã"), enquanto os pensamentos durante ataques de pânico geralmente se referem à situação imediata (por exemplo, "Vou desmaiar ou morrer agora" ou "Estou enlouquecendo"). Além disso, os comportamentos ansiosos incluem evitar situações ou aumentar a cautela (como planejar totalmente as direções com antecedência para evitar se perder), enquanto os comportamentos durante o pânico têm mais a ver com escapar ou procurar ajuda. Finalmente, os sintomas físicos durante a ansiedade geralmente são de longa duração e envolvem tensão muscular, inquietação e fadiga; em contraste, os sintomas dos ataques de pânico são mais abruptos e tendem a diminuir mais rapidamente do que os sintomas físicos da ansiedade, e incluem palpitações cardíacas, falta de ar e outros sintomas.

""", ['Formulário 3.2: Componentes da Ansiedade','https://drive.google.com/file/d/1c68H6yTWv_DkXAeh6j6C0j9-K8hugJn-/view?usp=drive_link']],
    'O ciclo do pânico': ["""Os sintomas físicos, pensamentos e comportamentos contribuem uns para os outros em um que é chamado de ciclo negativo. Em outras palavras, eles tendem a se alimentar mutuamente. Por exemplo, pensamentos negativos podem aumentar diretamente os sintomas físicos. Se nos dizemos que algo perigoso está prestes a acontecer (por exemplo, "Estou prestes a ter um ataque cardíaco"), então a tensão física aumentará porque nossos corpos liberam mais adrenalina e operam em ritmo mais rápido sempre que enfrentamos perigo. Por sua vez, um sintoma físico, como um coração acelerado, pode levar a mais pensamentos negativos. Isso é particularmente provável se você acreditar que os sintomas normais de tensão são perigosos (por exemplo, "O fato de que minha frequência cardíaca não diminuiu deve significar que algo está terrivelmente errado"). Comportamentos como agitação, caminhar de um lado para o outro e escapar de uma situação também podem aumentar os níveis de tensão física devido ao esforço físico envolvido.

Mais especificamente, o pensamento de que um coração acelerado é um sinal de doença cardíaca é assustador e produzirá uma frequência cardíaca ainda mais rápida. Por sua vez, uma frequência cardíaca mais rápida pode levar a crenças mais fortes de que algo está terrivelmente errado com o coração. Isso também pode levar a tentativas de obter ajuda médica. Tais pensamentos e comportamentos negativos podem novamente prolongar a aceleração do coração. Em outras palavras, pensamentos negativos levam ao medo, e o medo leva a mais sintomas físicos e comportamentos de fuga que se acumulam em mais pensamentos negativos, e assim por diante. O resultado final é um medo intenso ou pânico. Isso é chamado de ciclo de pânico. Outro exemplo é pensar que a falta de ar significa que você está prestes a sufocar. Esse pensamento causará mais tensão física e mais sintomas de falta de ar, bem como tentativas de respirar mais profundamente, o que por sua vez pode contribuir para a falta de ar (por razões descritas posteriormente), e assim por diante.

Em contraste, pensar que um coração acelerado é inofensivo e não motivo de preocupação interromperá esse ciclo negativo, com o resultado final de que o pânico não ocorre. Da mesma forma, perceber que a falta de ar não é um sinal de sufocamento iminente reduz as chances de um ataque de pânico.

Pense em um ataque de pânico recente e nos sintomas físicos, pensamentos e comportamentos, e como eles contribuíram uns para os outros. O que aconteceu primeiro? Foi um sintoma físico ou um pensamento? O que aconteceu em seguida? Seus sintomas físicos aumentaram, e no que isso o levou a pensar? Como você se comportou? Como suas reações influenciaram seus sintomas físicos?"""]
    
}