texts_choice = {
    
    'Razões para fazer registros': ["""Existem muitas razões pelas quais é importante manter registros regulares e contínuos de sua ansiedade. Em primeiro lugar, ataques de pânico, especialmente aqueles que parecem ocorrer sem motivo aparente, fazem com que as pessoas sintam que estão fora de controle e são vítimas de sua própria ansiedade. Aprender a ser um observador, em vez de uma vítima de sua própria ansiedade, é um primeiro passo para recuperar o controle. Através do registro, você aprenderá a observar quando, onde e em que circunstâncias seus ataques de pânico e ansiedade ocorrem.

Você aprenderá se seus ataques de pânico ocorrem quando você está sozinho ou com outras pessoas, depois de um dia estressante de trabalho ou nos fins de semana, no meio do dia ou no final do dia; se seus ataques de pânico são desencadeados por sentimentos de empolgação ao assistir a um evento esportivo na televisão, sentir-se superaquecido em uma área de compras lotada, sentir-se sufocado em um chuveiro quente, pensar em coisas horríveis que poderiam acontecer, ou relaxar e não ter mais nada para fazer além de se preocupar com seus medos. Novamente, compreender os fatores que fazem sua ansiedade e pânico aumentarem o ajudará a se sentir mais no controle e menos como uma vítima.

Em segundo lugar, você aprenderá a entender a maneira como vivencia o pânico e a ansiedade, em termos do que pensa, do que sente e do que faz. Essa compreensão é importante porque este programa é projetado especificamente para mudar o pensamento ansioso, os sentimentos ansiosos e os comportamentos ansiosos. Eles não podem ser alterados sem saber exatamente o que são.

Em terceiro lugar, o registro contínuo fornece informações muito mais precisas do que você obteria apenas se perguntasse a si mesmo: "Como tenho me sentido ultimamente?" Se lhe pedissem para descrever a última semana, você poderia julgá-la como sendo "muito ruim", quando, na verdade, pode ter havido várias vezes em que você se sentiu relativamente calmo. Quando a ansiedade está em sua mente com tanta frequência, é fácil esquecer os momentos em que você não estava ansioso. Como você provavelmente pode ver, pensar na semana anterior como "muito ruim" enquanto ignora os momentos "relativamente bons" durante a semana provavelmente o fará se sentir pior e mais ansioso. Na verdade, tais julgamentos negativos sobre como você tem se saído em geral podem contribuir para a ansiedade contínua. Mantendo registros contínuos, você não apenas se sentirá mais no controle, mas também menos ansioso ao reconhecer que seu estado de ânimo flutua e que há momentos em que você se sente menos ansioso do que em outros.

Por fim, o registro ajuda você a avaliar o progresso. Por esse motivo, recomendamos que você registre continuamente durante todo o programa. O registro contínuo permitirá que você aprecie os avanços que fez e ajudará a evitar que ataques de pânico ocasionais ofusquem o progresso que você alcançou.

Vamos rever todos os benefícios do registro contínuo, bem como as razões pelas quais ele é fundamental para este programa:

- Para ajudar você a se sentir mais no controle, identificando quando e onde os ataques de pânico são mais propensos a ocorrer;

- Para identificar as maneiras específicas pelas quais você experimenta a ansiedade, incluindo seus sentimentos físicos, seus pensamentos e seus comportamentos;

- Para ser capaz de avaliar com mais precisão seu nível de ansiedade e pânico; e

- Para avaliar o sucesso de seus esforços para mudar."""],


    'O propósito da ansiedade e do pânico': ["""A ansiedade e o pânico são estados emocionais naturais que são experimentados por todos que fazem parte da experiência de ser humano. A ansiedade é a reação que todos nós temos sempre que pensamos que algo ruim ou ameaçador pode acontecer. Essas coisas ameaçadoras podem incluir ameaças físicas, como a possibilidade de doença, acidente ou morte; ameaças sociais, como a possibilidade de constrangimento, rejeição ou ridicularização; ou ameaças mentais, como a possibilidade de enlouquecer, perder o controle ou perder a faculdade mental. As ameaças podem ser grandes (como a possibilidade de perder a vida) ou pequenas (como a possibilidade de se atrasar para um compromisso). A ansiedade é nossa maneira de nos prepararmos para enfrentar o desafio apresentado por essas ameaças. Ela nos ajuda a nos preparar e nos proteger do que está ameaçando.

A ansiedade não é má em si mesma e pode ser uma força produtiva e motivadora. Anos de pesquisa mostraram que ter alguma ansiedade melhora o desempenho. Ou seja, você se sai melhor no que está fazendo, seja na sala de aula ou no trabalho, quando a ansiedade está presente até certo nível. Imagine não ter absolutamente nenhuma ansiedade em uma entrevista de emprego - você estaria menos motivado para mostrar o seu melhor e enfrentar o desafio de conseguir o emprego. Alguns psicólogos chamaram a ansiedade de "a sombra da inteligência" porque nos motiva a pensar adiante e nos preparar para os desafios que podemos enfrentar. No entanto, a ansiedade pode variar em gravidade, desde um leve desconforto até uma angústia extrema. No extremo, a ansiedade pode interferir no que estamos fazendo. Imagine uma ansiedade extrema em uma entrevista de emprego que leva a uma concentração ruim e gagueira. Alguma ansiedade é útil para o aprendizado e o desempenho, enquanto muito ansiedade pode interferir negativamente nos mesmos processos.  

A ansiedade pode variar em frequência, desde episódios ocasionais até uma sensação aparentemente constante de desconforto. Quando a ansiedade é muito frequente, ela pode interferir na vida cotidiana. Os objetivos deste programa são diminuir a probabilidade de ficar ansioso desnecessariamente e diminuir a intensidade da ansiedade para que você possa funcionar normalmente. No entanto, o objetivo não é eliminar a ansiedade completamente.

Como essa discussão sobre ansiedade se relaciona com o transtorno de pânico? No caso do transtorno de pânico, a ansiedade é experimentada por causa da "ameaça" do pânico. O pânico é considerado ameaçador devido às crenças de que o pânico pode fazer com que você morra, perca o controle ou enlouqueça. Como você verá, essas crenças estão equivocadas porque os ataques de pânico na verdade não são prejudiciais em si."""
],

    'Os componentes da ansiedade': ["""Existem três partes principais nas emoções de ansiedade e pânico: sintomas físicos, pensamentos e comportamentos:

Sintomas Físicos: Esta parte envolve sintomas como batimentos cardíacos rápidos, dificuldade para respirar, estômago nervoso, diarreia, sudorese, tremores, dores de cabeça, dores de estômago, sensação de um nó na garganta, micção frequente e distúrbios visuais (todos esses mais associados a ataques de pânico) e fadiga, inquietação, tensão muscular e sensação de pressão na cabeça (mais associados à ansiedade), entre outros. Os sintomas físicos podem ser agudos, durando um curto período de tempo (como em ataques de pânico), ou podem ser prolongados, durando horas ou dias (como na ansiedade geral). Além disso, os sintomas físicos agudos podem variar de um ataque de pânico para o próximo. Em uma ocasião, você pode notar sintomas intensos de falta de ar, enquanto em outra ocasião pode perceber em vez disso um coração acelerado e pulsante.

Pensamentos: São as crenças, coisas que dizemos a nós mesmos ou imagens de uma iminente catástrofe ou algo terrível prestes a acontecer. Chamamos esses pensamentos de pensamentos negativos. Na maioria das vezes, os pensamentos durante ataques de pânico estão relacionados a catástrofes físicas imediatas (como desmaiar, morrer, ter um ataque cardíaco, tumor cerebral), catástrofes sociais (como zombarias ou ridicularizações) ou catástrofes mentais (como enlouquecer ou perder o controle). Os pensamentos durante a ansiedade se relacionam com coisas ruins que podem acontecer no futuro, como a perda do emprego ou o pior ataque de pânico de todos.

Comportamentos: São as coisas que fazemos, como andar de um lado para o outro, ficar inquieto ou escapar ou evitar lugares onde esperamos que a ansiedade e o pânico ocorram. Um exemplo de fuga é sair de um shopping assim que surgem sentimentos de ansiedade ou pânico. Um exemplo de evitação é não entrar em um shopping devido a preocupações de ter um ataque de pânico uma vez dentro. Outros comportamentos incluem procurar saídas ou maneiras de sair de situações, depender de objetos que fazem você se sentir melhor (esses são os objetos de segurança ou de superstição ) ou procurar ajuda (como em centros médicos).

Esses três componentes frequentemente diferem nos momentos em que você está ansioso em relação aos momentos em que está em pânico. Os pensamentos durante a ansiedade geralmente se relacionam com o futuro (por exemplo, "Meu chefe pode me dar uma avaliação negativa no final do ano" ou "Seria horrível se eu entrasse em pânico na festa de amanhã"), enquanto os pensamentos durante ataques de pânico geralmente se referem à situação imediata (por exemplo, "Vou desmaiar ou morrer agora" ou "Estou enlouquecendo"). Além disso, os comportamentos ansiosos incluem evitar situações ou aumentar a cautela (como planejar totalmente as direções com antecedência para evitar se perder), enquanto os comportamentos durante o pânico têm mais a ver com escapar ou procurar ajuda. Finalmente, os sintomas físicos durante a ansiedade geralmente são de longa duração e envolvem tensão muscular, inquietação e fadiga; em contraste, os sintomas dos ataques de pânico são mais abruptos e tendem a diminuir mais rapidamente do que os sintomas físicos da ansiedade, e incluem palpitações cardíacas, falta de ar e outros sintomas.

""", ['Formulário 3.2: Componentes da Ansiedade','https://drive.google.com/file/d/1c68H6yTWv_DkXAeh6j6C0j9-K8hugJn-/view?usp=drive_link']],
    'O ciclo do pânico': ["""Os sintomas físicos, pensamentos e comportamentos contribuem uns para os outros no que é chamado de ciclo negativo. Em outras palavras, eles tendem a se alimentar mutuamente. Por exemplo, pensamentos negativos podem aumentar diretamente os sintomas físicos. Se nos dizemos que algo perigoso está prestes a acontecer (por exemplo, "Estou prestes a ter um ataque cardíaco"), então a tensão física aumentará porque nossos corpos liberam mais adrenalina e operam em ritmo mais rápido sempre que enfrentamos perigo. Por sua vez, um sintoma físico, como um coração acelerado, pode levar a mais pensamentos negativos. Isso é particularmente provável se você acreditar que os sintomas normais de tensão são perigosos (por exemplo, "O fato de que minha frequência cardíaca não diminuiu deve significar que algo está terrivelmente errado"). Comportamentos como agitação, caminhar de um lado para o outro e escapar de uma situação também podem aumentar os níveis de tensão física devido ao esforço físico envolvido.

Mais especificamente, o pensamento de que um coração acelerado é um sinal de doença cardíaca é assustador e produzirá uma frequência cardíaca ainda mais rápida. Por sua vez, uma frequência cardíaca mais rápida pode levar a crenças mais fortes de que algo está terrivelmente errado com o coração. Isso também pode levar a tentativas de obter ajuda médica. Tais pensamentos e comportamentos negativos podem novamente prolongar a aceleração do coração. Em outras palavras, pensamentos negativos levam ao medo, e o medo leva a mais sintomas físicos e comportamentos de fuga que se acumulam em mais pensamentos negativos, e assim por diante. O resultado final é um medo intenso ou pânico. Isso é chamado de ciclo de pânico. Outro exemplo é pensar que a falta de ar significa que você está prestes a sufocar. Esse pensamento causará mais tensão física e mais sintomas de falta de ar, bem como tentativas de respirar mais profundamente, o que por sua vez pode contribuir para a falta de ar (por razões descritas posteriormente), e assim por diante.

Em contraste, pensar que um coração acelerado é inofensivo e não motivo de preocupação interromperá esse ciclo negativo, com o resultado final de que o pânico não ocorre. Da mesma forma, perceber que a falta de ar não é um sinal de sufocamento iminente reduz as chances de um ataque de pânico.

Pense em um ataque de pânico recente e nos sintomas físicos, pensamentos e comportamentos, e como eles contribuíram uns para os outros. O que aconteceu primeiro? Foi um sintoma físico ou um pensamento? O que aconteceu em seguida? Seus sintomas físicos aumentaram, e no que isso o levou a pensar? Como você se comportou? Como suas reações influenciaram seus sintomas físicos?"""],
    'Sintomas físicos e o pânico': ["""Pensamentos negativos contribuem para o pânico, principalmente quando relacionados à crença de que os sintomas físicos são prejudiciais. Portanto, é essencial entender com precisão esses sintomas físicos para perceber que não são prejudiciais.

Cientificamente, o medo imediato ou de curto prazo (ou seja, um ataque de pânico) é chamado de resposta de luta ou fuga. Seus efeitos visam a fugir do perigo ou, se isso falhar, lutar para sobreviver. O objetivo principal do pânico é nos proteger do perigo. Mesmo no mundo agitado de hoje, isso é relevante. Imagine-se atravessando uma rua quando um carro se aproxima rapidamente. Se você não sentisse medo, seria atingido. Na realidade, a resposta de luta ou fuga toma conta, e você sai do caminho. O objetivo do pânico é nos proteger, não nos prejudicar.

Quando o perigo é detectado, o cérebro envia mensagens para o sistema nervoso autônomo, que tem dois ramos: o sistema nervoso simpático e o parassimpático. O sistema simpático é responsável por liberar energia e preparar o corpo para a ação (lutar ou fugir), enquanto o parassimpático restaura o estado normal. A ativação do sistema simpático é responsável pela maioria dos sintomas de ataque de pânico.

O sistema simpático é um sistema tudo-ou-nada: quando é ativado, todas as suas partes respondem. Isso pode explicar por que a maioria dos ataques de pânico envolve muitos sintomas físicos, não apenas um ou dois. Além disso, o sistema simpático responde imediatamente, assim que o perigo está próximo. Isso é por que os sintomas físicos dos ataques de pânico podem ocorrer quase instantaneamente, em questão de segundos.

O sistema simpático libera duas substâncias químicas, adrenalina e noradrenalina, das glândulas adrenais nos rins. Essas substâncias são usadas como mensageiros pelo sistema simpático para continuar a atividade, o que pode durar algum tempo. No entanto, a atividade do sistema simpático é interrompida de duas maneiras:

As substâncias químicas adrenalina e noradrenalina são eventualmente destruídas por outras substâncias químicas no corpo.

O sistema nervoso parassimpático, que geralmente tem efeitos opostos ao sistema simpático, é ativado e restaura o estado normal.

Isso significa que o pânico não pode continuar para sempre nem atingir níveis cada vez mais prejudiciais. O sistema parassimpático impede o sistema simpático de se descontrolar.

A adrenalina e a noradrenalina levam algum tempo para serem completamente destruídas. Mesmo depois que o sistema simpático parou de responder, você pode se sentir tenso por algum tempo, pois as substâncias ainda estão em seu sistema. Isso é perfeitamente normal e inofensivo. Na verdade, isso tem um propósito: na natureza, o perigo muitas vezes retorna. É útil para nós permanecermos tensos para que possamos reativar rapidamente a resposta de luta ou fuga se o perigo retornar.

Cada efeito físico do sistema de luta ou fuga tem como objetivo nos preparar para lutar ou fugir, ou seja, nos proteger. Isso afeta nosso coração, fluxo sanguíneo, respiração, suor, pupilas, músculos e sistema digestivo, entre outras partes do corpo.

Efeitos Cardiovasculares:

A atividade no sistema simpático aumenta a frequência cardíaca e a força dos batimentos cardíacas. Isso melhora o fluxo sanguíneo, fornecendo mais oxigênio aos tecidos e removendo resíduos. Isso é vital para a preparação para a ação (lutar ou fugir), pois acelera o fluxo sanguíneo.

O fluxo sanguíneo é redirecionado, afastando-o de onde não é necessário (por meio do estreitamento dos vasos sanguíneos) e direcionando-o para onde é mais necessário (por meio da expansão dos vasos sanguíneos). Por exemplo, o sangue é desviado da pele, dedos e dedos dos pés, para reduzir o risco de lesões. Em vez disso, o sangue vai para os grandes músculos, como as coxas, o coração e os bíceps, que precisam de oxigênio para lutar ou fugir.

Essas mudanças físicas fazem o coração bater rápido e a pele ficar pálida e fria, principalmente ao redor das mãos e dos pés. Isso é uma reação normal em situações de medo ou ansiedade, indicando que o corpo está se preparando para agir.

Efeitos na Respiração:

A respiração fica mais rápida e profunda, pois o corpo precisa de mais oxigênio para lutar ou fugir. Às vezes, a respiração pode ficar desequilibrada e causar sintomas desconfortáveis, como falta de ar, sensação de sufocamento e dor ou aperto no peito.

Além disso, o suprimento de sangue para a cabeça pode ser reduzido. Isso não é perigoso, mas pode causar sintomas desagradáveis, como tontura, visão turva, confusão, sensação de irrealidade e ondas de calor. Esses sintomas físicos podem ser desconfortáveis, mas não indicam algo seriamente errado com você.

Efeitos nas Glândulas Sudoríparas:

A resposta de luta ou fuga aumenta a transpiração para resfriar o corpo e permitir que você continue lutando ou fugindo sem sofrer com o calor. A transpiração é um sintoma comum de ansiedade e pânico.
Outros Efeitos Físicos:

As pupilas dos olhos se dilatam para permitir a entrada de mais luz, ajudando a escanear o ambiente em busca de perigo. Isso faz sentido, já que o pânico e a ansiedade são reações à percepção de ameaça.

A boca fica seca devido à diminuição da salivação, e a atividade do sistema digestivo é reduzida para direcionar a energia para os músculos necessários para lutar ou fugir. Isso pode causar náuseas, sensação de peso no estômago e, às vezes, diarreia.

Muitos grupos musculares se contraem em preparação para a luta ou fuga, resultando em tensão, dores, tremores e tremedeira.

Outro efeito interessante é a liberação de analgésicos naturais pelo cérebro, reduzindo a sensação de dor quando estamos com medo. Isso nos permite continuar lutando ou fugindo, mesmo que estejamos feridos.

Além disso, ocorre a liberação de coagulantes e linfócitos no sangue, que ajudam a fechar feridas e reparar danos nos tecidos. A velocidade de liberação de glóbulos vermelhos também aumenta para transportar mais oxigênio no sangue, e o fígado libera açúcar armazenado para fornecer mais energia aos músculos.

Por fim, como a resposta de luta ou fuga ativa o corpo inteiro, o que requer muita energia, as pessoas geralmente se sentem cansadas e exaustas depois.

Resumindo, as mudanças físicas que causam os sintomas físicos do pânico e da ansiedade são protetoras, destinadas a nos ajudar a escapar ou enfrentar o perigo. Os sintomas são reais, mas não prejudiciais. É importante entender que esses sintomas são uma resposta normal do corpo a situações de estresse e não indicam uma ameaça grave à saúde."""    
],
'Por que ataques de pânico surgem "do nada"?': ["""Após sentir medo várias vezes de sintomas físicos, esse medo pode ocorrer "automaticamente". A qualidade "automática" é típica do que aprendemos em muitos casos. Pense quando você aprendeu a andar de bicicleta ou dirigir um carro. Inicialmente, exigia muita concentração e autoinstrução sobre o que fazer a cada passo do caminho. Gradualmente, tornou-se automático, andar de bicicleta e dirigir sem pensar conscientemente no que se está fazendo. E ainda assim, seus pensamentos automáticos ainda estão orientando o comportamento de como dirigir. A mesma coisa acontece com os pensamentos negativos associados ao pânico e à ansiedade. Com o tempo, eles podem se tornar automáticos, de modo que você não está ciente do que está pensando; no entanto, esses pensamentos ainda influenciam seus sentimentos e comportamentos. Porque você não está ciente de seus pensamentos, pode parecer que o pânico e a ansiedade vêm "do nada" - você simplesmente sente medo e não sabe por quê.

Outro processo automático é chamado condicionamento interoceptivo. Isso significa aprender a ter medo de sintomas físicos devido a experiências negativas anteriores associadas a esses sintomas. Por exemplo, imagine que sempre que você fica doente aparece uma cãibra muscular na perna. Muito em breve, você aprenderia a ter medo de cãibras musculares na perna, antecipando ficar muito doente. A mesma coisa acontece com o pânico; neste caso, no entanto, a cãibra muscular é um sintoma físico que ocorre durante o pânico (como um coração acelerado), e a doença é o terror causado por crenças de que você pode morrer, perder o controle ou enlouquecer. Uma vez que a possibilidade de morte ou alguma outra catástrofe esteja ligada a um coração acelerado, mudanças na frequência cardíaca podem causar medo automático, uma vez que o medo é condicionado. Consequentemente, até mesmo pequenas alterações na frequência cardíaca (causadas, por exemplo, por subir uma escada) que são normais e não o incomodaram antes de você experimentar o pânico podem fazer você ficar com medo. Na verdade, a mudança física pode ser tão sutil que você não está totalmente ciente disso, mas ainda assim isso faz você ter medo. Esta é outra razão pela qual os ataques de pânico às vezes parecem acontecer "do nada" - na verdade, eles são desencadeados por mudanças físicas sutis das quais você não está consciente, mas às quais seu corpo se condicionou a reagir.

Quando julgamentos sobre os sintomas físicos serem perigosos ocorrem automaticamente (ou seja, sem consciência), ou quando o medo é condicionado a sintomas físicos de intensidade mesmo que mínima, de modo que você não está ciente do que está respondendo, então os ataques de pânico parecem ocorrer do nada. Além disso, lembre-se de que nossos sistemas de resposta de emergência de luta ou fuga são projetados de tal forma que respondem instantaneamente (sem pensar conscientemente). Sem essa capacidade de resposta instantânea, não seríamos capazes de sobreviver, porque os perigos às vezes podem nos atingir muito rapidamente. A consequência em termos de ataques de pânico é que crenças e condicionamentos automáticos podem acontecer tão rapidamente que o resultado final - o ataque de pânico - parece acontecer sem tempo para pensar ou reagir. No entanto, na realidade, nosso medo é sempre desencadeado por algo. Ou seja, os sintomas físicos ou os pensamentos negativos sobre os sintomas físicos estão sempre presentes, mesmo que não sejam imediatamente óbvios.

Isso também é verdade para ataques de pânico que ocorrem a partir de um estado relaxado e para ataques de pânico que o acordam de um sono profundo (ou seja, ataques de pânico noturnos). Durante o relaxamento, os sentimentos físicos frequentemente são diferentes do normal, às vezes resultando em sensações de flutuação ou estar em transe. Se você tem medo de sensações físicas diferentes do normal, então os sentimentos físicos que você tem durante o relaxamento podem desencadear um ataque de pânico. Ataques de pânico noturnos são experimentados por cerca de metade das pessoas que sofrem de transtorno do pânico, e cerca de 25% têm ataques de pânico repetidos durante o sono.

Você pode perguntar: "Como os ataques de pânico noturnos podem ser desencadeados por sensações físicas"? Primeiro, é normal ter mudanças nos ritmos físicos durante o sono. Por exemplo, as taxas cardíacas e as taxas de respiração aumentam e diminuem em momentos diferentes durante a noite. Em segundo lugar, temos a capacidade de responder a eventos significativos durante o sono. Pense na mãe que acorda em resposta ao menor som de seu bebê recém-nascido, enquanto dorme com outros sons mais altos, como caminhões passando em uma rodovia próxima. Outro exemplo seriam os soldados em combate que têm a capacidade de dormir com o som de aviões aliados, mas acordam com o som de aviões inimigos. Assim, se as mudanças físicas forem significativas (ou seja, se forem assustadoras), é compreensível que as mudanças físicas que normalmente ocorrem durante o sono possam fazer alguém acordar em um ataque de pânico, da mesma forma que os ataques de pânico ocorrem durante o dia. Isso é especialmente provável de acontecer se as mudanças físicas ocorrerem em um momento durante o sono em que é mais fácil acordar. Por exemplo, é muito difícil acordar de um sono profundo e do sono com movimento rápido dos olhos (REM) quando ocorrem sonhos, mas é mais fácil acordar das Etapas 2 e 3 do sono, que é quando a maioria dos ataques de pânico noturnos ocorre. É por isso que não são sonhos ou pesadelos que causam ataques de pânico noturnos, um equívoco comum."""],

}